[run]
  deadline = "2m"

[linters-settings]

  [linters-settings.govet]
    check-shadowing = true

  [linters-settings.gocyclo]
    min-complexity = 12.0

  [linters-settings.maligned]
    suggest-new = true

  [linters-settings.goconst]
    min-len = 3.0
    min-occurrences = 3.0

  [linters-settings.misspell]
    locale = "US"
    ignore-words = ["hardlinked", "behaviour"]

[linters]
  enable-all = true
  disable = [
    "maligned",
    "lll",
    "dupl",
    "prealloc",
    "scopelint",
    "wsl",
    "stylecheck",
    "testpackage",
    "nlreturn",
    "godot",
  ]

[issues]
  exclude-use-default = false
  max-per-linter = 0
  max-same = 0
  exclude = ["G204"]

 [[issues.exclude-rules]]
    path = "(.+)_test.go"
    linters = ["funlen"]

  [[issues.exclude-rules]]
    path = "branch/branch.go"
    text = "func name will be used as branch.BranchName by other packages"
  [[issues.exclude-rules]]
    path = "push/push_gen.go"
    text = "func name will be used as push.PushOption by other packages"
  [[issues.exclude-rules]]
    path = "doc.go"
    text = "don't use an underscore in package name"
  [[issues.exclude-rules]]
    path = "internal/generator.go"
    text = "`expCmd(.+)` is a global variable"
  [[issues.exclude-rules]]
    path = "internal/generator.go"
    text = "G306:"