language: go

go:
  - 1.13.x
  - 1.x

sudo: false

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.21.0
  - golangci-lint --version

install:
  - go mod tidy
  - git diff --exit-code go.mod
#  - git diff --exit-code go.sum
  - go mod download
