language: go

go:
  - 1.14.x
  - 1.x

sudo: false

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.30.0
  - golangci-lint --version

install:
  - go mod tidy
  - git diff --exit-code go.mod
  - git diff --exit-code go.sum
  - go mod download
