language: go

go:
  - 1.9.x
  - 1.x
  - tip

sudo: false

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.10.2
  - golangci-lint --version
